-- SCRUM-83: paste this whole file into your development Supabase SQL Editor.
-- This one file handles both an empty database and the original UUID setup.
-- Safe to run again: the five fixed IDs keep the same users without duplicates.
begin;

create table if not exists public.app_users (
    -- IDs 1-5 belong to the demo users; future users get 6, 7, 8, ... automatically.
    id integer generated by default as identity (start with 6) primary key,
    display_name text not null,
    role text not null check (
        role in ('Organiser', 'Coordinator', 'Venue Staff', 'Tech Support', 'Attendee')
    ),
    is_demo boolean not null default false
);

-- Upgrade the original demo UUIDs to IDs 1-5 if needed.
-- For a new database or one already using numbers, this block does nothing.
lock table public.app_users in access exclusive mode;

do $$
begin
    if exists (
        select 1 from information_schema.columns
        where table_schema = 'public' and table_name = 'app_users'
          and column_name = 'id' and data_type = 'uuid'
    ) then
        alter table public.app_users alter column id drop default;

        -- Unexpected UUIDs fail the primary key's NOT NULL check, rolling back
        -- this whole script so other users are not accidentally changed.
        alter table public.app_users
            alter column id type integer using (
                case id::text
                    when '00000000-0000-4000-8000-000000000001' then 1
                    when '00000000-0000-4000-8000-000000000002' then 2
                    when '00000000-0000-4000-8000-000000000003' then 3
                    when '00000000-0000-4000-8000-000000000004' then 4
                    when '00000000-0000-4000-8000-000000000005' then 5
                end
            );

        alter table public.app_users
            alter column id add generated by default as identity (start with 6);
    end if;
end $$;

-- Flask's backend secret key accesses this table as the service_role database role.
-- Browser/anonymous clients must not be able to read or change these identities.
alter table public.app_users enable row level security;
revoke all on public.app_users from anon, authenticated;
grant select on public.app_users to service_role;

insert into public.app_users (id, display_name, role, is_demo)
values
    (1, 'Demo Organiser', 'Organiser', true),
    (2, 'Demo Coordinator', 'Coordinator', true),
    (3, 'Demo Venue Staff', 'Venue Staff', true),
    (4, 'Demo Tech Support', 'Tech Support', true),
    (5, 'Demo Attendee', 'Attendee', true)
on conflict (id) do update set
    display_name = excluded.display_name,
    role = excluded.role,
    is_demo = excluded.is_demo;

commit;

-- You should see the same five demo users after every run.
select id, display_name, role from public.app_users where is_demo = true order by id;
